-- Personas de apoyo sin cuenta de acceso. Ejecutar en Supabase SQL Editor.
create table if not exists public.personal_apoyo (
  id bigint generated by default as identity primary key,
  nombres text not null check (length(btrim(nombres)) > 0),
  apellidos text not null check (length(btrim(apellidos)) > 0),
  dni text not null check (dni ~ '^[0-9]{8}$'),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint personal_apoyo_dni_unique unique (dni)
);

-- Si ya se habia creado una version anterior con mas campos, conservar sus
-- filas y permitir que las nuevas altas usen solo nombres, apellidos y DNI.
alter table public.personal_apoyo
  add column if not exists nombres text,
  add column if not exists apellidos text,
  add column if not exists activo boolean not null default true;

do $$ begin
  if exists (select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'personal_apoyo' and column_name = 'nombre') then
    execute $upgrade$
      update public.personal_apoyo
      set nombres = coalesce(nullif(nombres, ''), split_part(btrim(nombre), ' ', 1)),
          apellidos = coalesce(nullif(apellidos, ''), nullif(btrim(substr(btrim(nombre), length(split_part(btrim(nombre), ' ', 1)) + 1)), ''), 'Sin especificar')
      where nombres is null or apellidos is null
    $upgrade$;
    alter table public.personal_apoyo alter column nombre drop not null;
  end if;
  if exists (select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'personal_apoyo' and column_name = 'fecha_ingreso') then
    alter table public.personal_apoyo alter column fecha_ingreso drop not null;
  end if;
end $$;

create index if not exists personal_apoyo_nombre_idx on public.personal_apoyo (apellidos, nombres);
create unique index if not exists personal_apoyo_dni_idx on public.personal_apoyo (dni) where dni is not null;
alter table public.personal_apoyo enable row level security;
revoke all on public.personal_apoyo from anon, authenticated;
grant select, insert, update on public.personal_apoyo to service_role;
grant usage, select on sequence public.personal_apoyo_id_seq to service_role;
notify pgrst, 'reload schema';
